export const ROOM_SCENES = Object.freeze([
  Object.freeze({
    id: "warm-showroom",
    label: "Warm",
    description: "Warm walnut showroom",
    background: "#d8d0c4",
    wall: "#e9dfd1",
    floor: "#bda98e",
    rug: "#d8cabb",
    accent: "#76563d",
    sky: "#fff8ec",
    ground: "#746b61",
    hemisphereIntensity: 0.66,
    keyColor: "#fff3df",
    keyIntensity: 1.34,
    fillColor: "#e9edf0",
    fillIntensity: 0.38,
    rimColor: "#f4dfc3",
    rimIntensity: 0.5,
    environmentIntensity: 0.46,
    shadowOpacity: 0.45,
  }),
  Object.freeze({
    id: "stone-gallery",
    label: "Gallery",
    description: "Natural stone gallery",
    background: "#d9dcda",
    wall: "#e4e5e1",
    floor: "#bfc0ba",
    rug: "#d1d0c9",
    accent: "#d0d0ca",
    sky: "#ffffff",
    ground: "#747874",
    hemisphereIntensity: 0.72,
    keyColor: "#fbfdff",
    keyIntensity: 1.5,
    fillColor: "#e4edf2",
    fillIntensity: 0.46,
    rimColor: "#f2eee5",
    rimIntensity: 0.38,
    environmentIntensity: 0.56,
    shadowOpacity: 0.4,
  }),
  Object.freeze({
    id: "evening-lounge",
    label: "Evening",
    description: "Intimate evening lounge",
    background: "#292b29",
    wall: "#343732",
    floor: "#3e3a34",
    rug: "#625b50",
    accent: "#c59659",
    sky: "#f2dfbf",
    ground: "#151715",
    hemisphereIntensity: 0.42,
    keyColor: "#ffdca8",
    keyIntensity: 1.08,
    fillColor: "#aab7bd",
    fillIntensity: 0.22,
    rimColor: "#ffc980",
    rimIntensity: 0.7,
    environmentIntensity: 0.28,
    shadowOpacity: 0.54,
  }),
]);

export const DEFAULT_ROOM_SCENE_ID = ROOM_SCENES[0].id;

export function getRoomScene(sceneId) {
  return ROOM_SCENES.find((scene) => scene.id === sceneId) ?? ROOM_SCENES[0];
}
